name: Pull Changes

on:
  push:
    branches:
      - main # Adjust this based on your branch name

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Changes
      run: git pull

