name: Pull Changes and Build

on:
  push:
    branches:
      - main

jobs:
  pull_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch and Pull Changes
      run: |
        git fetch
        git pull


